Feature/alichry
doctrine/DoctrineModule pull request #712
Opened 2020-11-13 21:23 UTC by TomHAnderson

This is a cherry-pick of https://github.com/doctrine/DoctrineModule/pull/702 to 4.0.x

2020-11-13 21:23 UTC, TomHAnderson commented
From @alichry 

This PR allows specifying the session container name and member to use in the underlying Session Storage instead of using the default. In case one of the new options are set, the StorageFactory creates a local instance of the Session Storage. Otherwise, it will retrieve the default aliased Session Storage 'DoctrineModule\Authentication\Storage\Session'

The Session Storage instance wrapper (ObjectRepository) is still cached by service manager.

2020-11-13 22:14 UTC, TomHAnderson commented
Beyond what @alichry submitted I created a unit test for their work.

2020-11-14 08:05 UTC, greg0ire commented on tests/DoctrineModuleTest/Service/Authentication/StorageFactoryTest.php
> +            ->expects($this->at(0))
`at` is deprecated in recent versions of PHPUnit, you should avoid it or will mean more work when migrating.

If you mean to check that the service manager is called, use

```suggestion
            ->expects($this->once())
```

If you mean to just set up the service manager, then this is a stub, and you can drop the line entirely (and use `createStub` over `createMock`.

Another solution could be to use a real service manager instead of a mock.

2020-11-14 20:49 UTC, TomHAnderson commented on tests/DoctrineModuleTest/Service/Authentication/StorageFactoryTest.php
> +            ->expects($this->at(0))
It is a mock, not a stub.  Changed to use `onConsecutiveCalls` and removed `->at()` calls.

2020-11-14 21:09 UTC, greg0ire approved these changes

2020-11-14 22:20 UTC, TomHAnderson commented
Rebase to correct commit message for phpcs

2020-11-14 23:38 UTC, SenseException requested changes

2020-11-14 23:38 UTC, SenseException commented on src/DoctrineModule/Service/Authentication/StorageFactory.php
> +                    $options->getSessionMember()
The variables should be used here.

2020-11-15 15:45 UTC, alichry commented
Thank you for adding the required test case and considering this feature in the next release :)

2020-11-16 18:11 UTC, SenseException approved these changes

2020-11-16 18:38 UTC, merged