fix #728 : DriverFactory incompatible with AttributeDriver
doctrine/DoctrineModule pull request #730
Opened 2021-09-21 08:59 UTC by fezfez

2021-09-21 09:22 UTC, TomHAnderson commented
Hi @fezfez ,

Your class name is wrong.  Thanks for the PR.  Can you add a unit test too?

2021-09-21 09:50 UTC, fezfez commented
hi @TomHAnderson

After checking everywhere, the class does not exist in doctrine/persistance, so i've added doctrine/orm in dev deps to add a test

2021-09-22 13:58 UTC, fezfez commented
@TomHAnderson : do you have time to check this and make release soon ?

2021-10-02 22:10 UTC, TomHAnderson commented on tests/DoctrineModuleTest/Service/DriverFactoryTest.php
> +    public function testCreateAttributDriver(): void
Class name is incorrect

2021-10-02 22:11 UTC, TomHAnderson requested changes
Rebase these two commits into a single commit please.

2021-10-12 19:43 UTC, driehle commented on tests/DoctrineModuleTest/Service/DriverFactoryTest.php
> +    public function testCreateAttributDriver(): void
```suggestion
    public function testCreateAttributeDriver(): void
```

2021-10-15 12:29 UTC, driehle commented
@fezfez Could you please rebase into a single commit and fix the class name?

2021-10-18 13:07 UTC, driehle commented
Closing in favour of #734 as fezfez has disabled edits from maintainers in this PR.

2021-10-18 13:07 UTC, closed without merging