Allow laminas form 3.0 while keeping BC
doctrine/DoctrineModule pull request #731
Opened 2021-10-06 09:43 UTC by driehle

This PR is an alternative to #726. In contrast to #726 this PR keeps backward compatibility by using polyfills. Technically, there are now two different implementations of the form elements, one targeted at laminas-form v2 and a different one targeted at laminas-form v3. Using Composers autoload feature, the implementation corresponding to the installed laminas-form version is loaded and put into the right place using `class_alias`.

In case you are skeptical about this technique, I'd like to refer to laminas-form 2.15.x series, which itself used the same principle to support both laminas-servicemanager v2 and v3. Have a look at their [composer.json](https://github.com/laminas/laminas-form/blob/2.15.x/composer.json#L65), [autoload file](https://github.com/laminas/laminas-form/blob/2.15.x/autoload/formElementManagerPolyfill.php) and [polyfills](https://github.com/laminas/laminas-form/tree/2.15.x/src/FormElementManager).

I based this PR on #727 for two reasons: First, #727 is already approved though not yet merged. Second, #727 (specifically 468bd15d924e409ebba5e3eba20d954f5c7a8d9d) contains a fix for the unit tests which is needed for newer laminas-stdlib version, as they use strict types.

2021-10-06 11:17 UTC, driehle commented
Please note that I have updated the Github workflows:
 - Unit tests are now running with both highest and lowest dependencies for all PHP versions, this effectively tests both laminas-form 2.x and 3.x
 - Coverage reports are uploaded to Codecov again (seems like no-one has updated that since Travis shut down...)

2021-10-18 20:18 UTC, snapshotpl approved these changes

2021-10-18 21:25 UTC, greg0ire commented on .github/workflows/coding-standards.yml
> +        run: "vendor/bin/phpcs -q --no-colors --report=checkstyle | cs2pr"
Please configure your IDE to always add a newline at end of file, this will make the red pictogram disappear.

2021-10-18 21:25 UTC, greg0ire commented on .github/workflows/coding-standards.yml
> +name: "Coding Standards"
Let's reuse the centralized workflow here?

2021-10-18 21:25 UTC, greg0ire commented on .github/workflows/continuous-integration.yml
> +          directory: "reports"
This looks generic enough that you could reuse the centralized workflow here too.

2021-10-19 09:15 UTC, driehle commented on .github/workflows/coding-standards.yml
> +        run: "vendor/bin/phpcs -q --no-colors --report=checkstyle | cs2pr"
Sorry, haven't configured all workstations accordingly yet. Will be fixed.

2021-10-19 09:15 UTC, driehle commented on .github/workflows/coding-standards.yml
> +name: "Coding Standards"
Agree

2021-10-19 09:15 UTC, driehle commented on .github/workflows/continuous-integration.yml
> +          directory: "reports"
I'll want to add different testing for laminas-form ^2.0 and ^3.0, similar to what is in `doctrine/orm` as you suggested. I think then I can't use the centralized workflow anymore?

2021-10-19 21:13 UTC, SenseException commented on src/DoctrineModule/Form/Element/ObjectMultiCheckboxV3Polyfill.php
> +    }
Does it make sense to move identical methods into a trait too?

2021-10-19 21:39 UTC, driehle commented on src/DoctrineModule/Form/Element/ObjectMultiCheckboxV3Polyfill.php
> +    }
I think you can't call `parent` from within a trait, can you? I remember I tried implementing it that way and there was this issue.

2021-10-19 23:23 UTC, TomHAnderson requested changes

2021-10-19 23:23 UTC, TomHAnderson commented on src/DoctrineModule/Form/Element/HasProxy.php
> +trait HasProxy
I dislike the name of this trait.  HasProxy implies a boolean but `getProxy` will always return a Proxy.  I would prefer this be renamed to `trait GetProxy`.

2021-10-19 23:23 UTC, TomHAnderson commented on src/DoctrineModule/Form/Element/ObjectMultiCheckboxV3Polyfill.php
> +    use HasProxy;
Change to `GetProxy`

2021-10-19 23:25 UTC, TomHAnderson commented on src/DoctrineModule/Form/Element/HasProxy.php
> +trait HasProxy
Apply change to all polyfills

2021-10-20 07:01 UTC, driehle commented on src/DoctrineModule/Form/Element/HasProxy.php
> +trait HasProxy
Trait now renamed to `GetProxy`

2021-10-20 11:17 UTC, driehle commented on src/DoctrineModule/Form/Element/ObjectMultiCheckboxV3Polyfill.php
> +    }
And there are discussions, that a trait should never override a method, see e.g. https://softwareengineering.stackexchange.com/questions/371067/should-a-trait-refer-to-parent-methods. Therefore, I would like to refrain from moving this into a trait somehow.

2021-10-20 18:42 UTC, TomHAnderson approved these changes

2021-10-20 19:44 UTC, driehle commented
Rebased on current `4.2.x`. @SenseException are you fine with the trait?

2021-10-21 15:07 UTC, merged