Switch to PSR-4 and move classes accordingly
doctrine/DoctrineModule pull request #737
Opened 2021-10-18 20:15 UTC by driehle

Since [doctrine-laminas-hydrator](https://github.com/doctrine/doctrine-laminas-hydrator) is and has always been using PSR-4, this project should follow. This PR switches from PSR-0 to PSR-4 and moves all classes in the right places, effectively droping one level of folder hierarchy in both `src` and `test`. 

I'd like to target this at the next minor release, i.e. 4.2.0.

2021-10-18 21:22 UTC, greg0ire reviewed
Good move 👍

2021-10-18 21:22 UTC, greg0ire commented on composer.json
> +            "DoctrineModuleTest\\": "test/"
This change is not justified or mentioned in the description of your PR / in your commit message.
I don't see why we should diverge from other Doctrine repositories on this (or from https://github.com/php-pds/skeleton).
Also, the change is incomplete, there is an occurrence of `tests` here:
https://github.com/doctrine/DoctrineModule/blob/662362af298d25a305d62e96931c0a3608078b40/.gitattributes#L1

2021-10-18 22:09 UTC, driehle commented on composer.json
> +            "DoctrineModuleTest\\": "test/"
In `doctrine-laminas-hydrator` and `DoctrineORMModule` the folder name is `test`. I wanted to keep it the same. In `DoctrineMongoODMModule` it is `tests`, we can alternatively change everything to `tests`. Would you prefer that?

2021-10-19 08:47 UTC, driehle commented on composer.json
> +            "DoctrineModuleTest\\": "test/"
As discussed on Slack, we'll keep `tests` here and adapt the other repositories accordingly.

2021-10-19 20:14 UTC, greg0ire commented on .gitignore
> +/.idea
Please, let's remove OS and IDE-specific directories, the list can grow indefinitely otherwise. People should use a global gitignore for this instead: https://greg0ire.fr/git-gud/#/23

2021-10-19 23:13 UTC, TomHAnderson commented
@Ocramius I wanted to do this years ago but was told then that the Doctrine standard is PSR-0.  Has that changed?  Can we go ahead with PSR-4 (this has my recommendation)

2021-10-20 06:37 UTC, greg0ire commented
We've had a discussion about this BTW: https://github.com/orgs/doctrine/teams/doctrinecore/discussions/27

2021-10-20 06:54 UTC, driehle commented
Plus, doctrine-laminas-hydrator has been using PSR-4 ever since and I strongly dislike having different standards across the Laminas-related projects. Porting doctrine-laminas-hydrator from PSR-4 to PSR-0, something which is essentially dead, does not make any sense to me.

2021-10-20 07:14 UTC, driehle commented on .gitignore
> +/.idea
Updated

2021-10-20 18:35 UTC, TomHAnderson requested changes

2021-10-20 18:35 UTC, TomHAnderson commented on .gitignore
> +/phpcs.xml.dist
I don't think `phpcs.xml.dist` should be in the ignore list.

2021-10-20 18:41 UTC, driehle commented on .gitignore
> +/phpcs.xml.dist
Indeed, there should be `phpcs.xml` instead of `phpcs.xml.dist`, and there should be `phpunit.xml` as well, which is currently still missing. I'm going to fix this.

2021-10-20 18:45 UTC, TomHAnderson commented on .gitignore
> +/phpcs.xml.dist
I disagree.  `phpcs.xml` and `phpunit.xml` are the purview of the developer and not the package.  It is correct to ignore them in .gitignore and distribute the `.dist` versions.

2021-10-20 18:47 UTC, TomHAnderson approved these changes

2021-10-20 18:49 UTC, driehle commented on .gitignore
> +/phpcs.xml.dist
Yes, excactly what I meant, but they way I wrote it down was misleading, sorry. I meant that there should be `phpcs.xml` and `phpunit.xml` on the `.gitignore`, but it was easy to understand the other way round. :-)

2021-10-20 19:36 UTC, merged