Removed integration with laminas-console and laminas-mvc-console
doctrine/DoctrineModule pull request #760
Opened 2021-12-21 14:28 UTC by driehle

2021-12-21 21:51 UTC, snapshotpl requested changes

2021-12-21 21:51 UTC, snapshotpl commented on src/Module.php
>      private $serviceManager;
After remove `GetConsoleUsage` can be removed

2021-12-21 22:14 UTC, driehle commented on src/Module.php
>      private $serviceManager;
Hm, the file src/GetConsoleUsage.php is already removed, or what do you mean?

2021-12-21 22:48 UTC, SenseException commented on src/Module.php
>      private $serviceManager;
The property doesn't seem to be in use anymore. And what about `onBootstrap()`?

2021-12-22 08:23 UTC, driehle commented on src/Module.php
>      private $serviceManager;
Ah, I see. Fixed with 4f5dcd9.

2021-12-23 00:34 UTC, TomHAnderson approved these changes

2021-12-23 05:35 UTC, merged