Require laminas-form 3.x, drop support for laminas-form 2.x
doctrine/DoctrineModule pull request #761
Opened 2021-12-21 14:39 UTC by driehle

2021-12-21 22:43 UTC, SenseException requested changes

2021-12-21 22:43 UTC, SenseException commented on .github/workflows/continuous-integration.yml
> -        laminas-form-version:
The step "Upload coverage file" still uses `laminas-form-version`

2021-12-22 08:26 UTC, driehle commented on .github/workflows/continuous-integration.yml
> -        laminas-form-version:
Thanks, rebased and fixed in e47bb55.

2021-12-23 00:28 UTC, TomHAnderson approved these changes

2021-12-23 05:36 UTC, merged