Mark `Module`, `ConfigProvider`, option classes and factories as final
doctrine/DoctrineModule pull request #766
Opened 2021-12-23 09:31 UTC by driehle

**Caution:** BC Break

The `Module` and `ConfigProvider` classes, as well as the option classes and all factories are no valid extension points. They are now marked as final.

2021-12-23 20:55 UTC, TomHAnderson approved these changes

2021-12-23 21:24 UTC, SenseException requested changes

2021-12-23 21:24 UTC, SenseException commented on src/Validator/Service/AbstractValidatorFactory.php
> + * Base validator factory to be extended
If you want a description for the class, I recommend to remove the extended part.

```suggestion
 * Base validator factory
```

1. It's abstract so it needs to be extended
2. If it's internal, it shouldn't invite to be extended outside of the DoctrineModule

2021-12-26 20:48 UTC, driehle commented on src/Validator/Service/AbstractValidatorFactory.php
> + * Base validator factory to be extended
fixed with c190ce5

2021-12-26 21:05 UTC, driehle commented
Rebased on current `5.0.x`

2021-12-27 20:33 UTC, SenseException approved these changes

2021-12-27 21:25 UTC, merged