Feat/merge drop php74
doctrine/DoctrineModule pull request #804
Opened 2023-04-18 23:42 UTC by TomHAnderson

This is a continuation of #799 with fixes for lastest code

2023-04-23 21:30 UTC, Ocramius requested changes

2023-04-23 21:30 UTC, Ocramius commented on psalm.xml
> +    findUnusedCode="false"
Should probably be `true` and expand the baseline

2023-04-23 21:30 UTC, Ocramius commented on src/Authentication/Adapter/ObjectRepository.php
> +    public function __construct(array|AuthenticationOptions $options = [], ?Inflector $inflector = null)
I'm OK with adding type declarations, but be very careful with added native types, since you may run into BC breaks

2023-04-23 21:30 UTC, Ocramius commented on src/Validator/ObjectExists.php
> +    protected mixed $fields = null;
This type change seems invalid

2023-04-23 21:32 UTC, TomHAnderson commented on src/Authentication/Adapter/ObjectRepository.php
> +    public function __construct(array|AuthenticationOptions $options = [], ?Inflector $inflector = null)
A new major version, 6.0.x, allows for BC breaks

2023-04-24 19:08 UTC, TomHAnderson commented on psalm.xml
> +    findUnusedCode="false"
```
When true, Psalm will attempt to find all unused code (including unused variables), the equivalent of running with --find-unused-code. Defaults to false.
```

This value will default to true in psalm 6.  I want to leave it as-is at this time because there is a lot of unused code in the library (a result of incomplete unit tests?)

2023-04-24 19:15 UTC, TomHAnderson commented on src/Validator/ObjectExists.php
> +    protected mixed $fields = null;
The fields property is typecast to an array in `validateFields()` thereby allowing objects with `ArrayAccess`. 

This object is not a final class so keeping this as `mixed` is appropriate for typed properties.

2023-04-24 19:21 UTC, TomHAnderson commented on src/Validator/ObjectExists.php
> +    protected mixed $fields = null;
Annotation dropped in d3ea2f98bbaed8bdbf666674543f0819e77bdeed

2023-05-10 19:23 UTC, merged