Support for PHP 8.3
doctrine/DoctrineModule pull request #828
Opened 2024-01-09 23:17 UTC by TomHAnderson

2024-01-11 20:35 UTC, SenseException approved these changes

2024-01-11 20:35 UTC, SenseException commented on src/Form/Element/ObjectMultiCheckbox.php
> +     * @return array<int<0, max>|string, array{attributes?: array<string, scalar|null>, disabled?: bool, label: non-empty-string, label_attributes?: array<string, scalar|null>, selected?: bool, value
Maybe this can be put into a type and used with import-type. Does Psalm and PHPStan share a common understanding with an annotation for importing a type?

2024-01-11 20:50 UTC, driehle requested changes
Please update PHP version of the other workflows to 8.2, i.e. coding standards, static analysis and composer lint. They need to run with the latest version, as the minimal version is automatically inflected.

2024-01-14 19:37 UTC, TomHAnderson commented
Return types are now imported from Laminas types.  Workflows updated to 8.2

2024-01-17 13:53 UTC, driehle approved these changes
LGTM

2024-01-17 13:54 UTC, driehle commented
This must be a new minor according to our rules, i.e. 6.1.0

2024-01-17 13:54 UTC, merged